from setuptools import setup

setup(
    name="lm-heuristic",
    version="",
    packages=[
        "lm_heuristic",
        "lm_heuristic.sentence_score",
        "lm_heuristic.tree",
        "lm_heuristic.utils",
        "lm_heuristic.heuristic",
        "lm_heuristic.evaluation",
        "lm_heuristic.tree_search",
        "lm_heuristic.tree_search.random",
        "lm_heuristic.tree_search.mcts"
    ],
    install_requires=[
        "matplotlib",
        "torch",
        "pandas",
        "seaborn",
        "nltk",
        "numpy",
        "transformers",
    ],
    url="https://github.com/dldk-gael/lm-heuristic",
    license="",
    author="Gaël de Léséleuc",
    author_email="gael@de-leseleuc.com",
    description="Package to found the most natural sentence that can be generated by a given context-free grammar",
)
